app/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('clients.urls')),
    path('', include('suppliers.urls')),
    path('', include('bank_accounts.urls')),
    path('', include('companies.urls')),
    path('', include('transactions.urls'))
]

bank_accounts/urls.py
from django.urls import path
from .views import BankAccountListView, BankAccountCreateView, BankAccountDetailView, BankAccountUpdateView, BankAccountDeleteView


urlpatterns = [
    path('bank_accounts/list/', BankAccountListView.as_view(), name='bank_account_list'),
    path('bank_accounts/create/', BankAccountCreateView.as_view(), name='bank_account_create'),
    path('bank_accounts/detail/<int:pk>/', BankAccountDetailView.as_view(), name='bank_account_detail'),
    path('bank_accounts/update/<int:pk>/', BankAccountUpdateView.as_view(), name='bank_account_update'),
    path('bank_accounts/delete/<int:pk>/', BankAccountDeleteView.as_view(), name='bank_account_delete')
]

bank_accounts/models.py
from django.db import models
from companies.models import Company


class BankAccount(models.Model):

    class AccountType(models.TextChoices):
        CONTA_CORRENTE = 'CC', 'Conta Corrente'
        CONTA_POUPANCA = 'CP', 'Conta Poupança'
        CONTA_PAGAMENTO = 'CPG', 'Conta Pagamento'
        CONTA_INVESTIMENTO = 'CI', 'Conta de Investimentos'
        CONTA_EMPRESARIAL = 'CE', 'Conta Empresarial'

    bank = models.CharField(verbose_name='Nome do Banco', max_length=50)
    account_balance = models.FloatField(verbose_name='Saldo da Conta', default=0)
    agency_number = models.CharField(verbose_name='Número da Agência Bancária', max_length=4)
    account_number = models.CharField(verbose_name='Número da Conta', max_length=20)
    account_type = models.CharField(verbose_name='Tipo de conta bancária', max_length=60, choices=AccountType.choices, default=AccountType.CONTA_EMPRESARIAL)
    account_company = models.ForeignKey(verbose_name='Empresa proprietária da conta', to=Company, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['bank']
        verbose_name = 'Contas Bancárias'

    def __str__(self):
        return self.bank

bank_accounts/forms.py
from django import forms
from .models import BankAccount


class BankAccountForm(forms.ModelForm):

    class Meta:
        model = BankAccount
        fields = ['bank', 'account_balance', 'agency_number', 'account_number', 'account_type']

        widgets = {
            'bank': forms.TextInput(attrs={'class': 'form-control'}),
            'account_balance': forms.NumberInput(attrs={'class': 'form-control'}),
            'agency_number': forms.TextInput(attrs={'class': 'form-control'}),
            'account_number': forms.TextInput(attrs={'class': 'form-control'}),
            'account_type': forms.Select(attrs={'class': 'form-control'})
        }

        labels = {
            'bank': 'Instituição/Banco',
            'account_balance': 'Saldo Da Conta',
            'agency_number': 'Número da Agência da Conta',
            'account_number': 'Número da Conta',
            'account_type': 'Tipo de Conta'
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance and self.instance.pk:
            self.fields.pop('account_balance')

bank_accounts/views.py
from django.views import generic
from django.urls import reverse_lazy
from .models import BankAccount
from .forms import BankAccountForm
from authentication.models import UserCompany
from django.shortcuts import redirect


class BankAccountListView(generic.ListView):
    model = BankAccount
    template_name = 'bank_account_list.html'
    context_object_name = 'bank_accounts'

    def get_queryset(self):
        queryset = super().get_queryset()

        bank = self.request.GET.get('bank')

        if bank:
            queryset = queryset.filter(bank__icontains=bank)
        
        return queryset


class BankAccountCreateView(generic.CreateView):
    model = BankAccount
    template_name = 'bank_account_create.html'
    form_class = BankAccountForm
    success_url = reverse_lazy('bank_account_list')

    def form_valid(self, form):
        bank_account = form.save(commit=False)
        try:
            user_company = UserCompany.objects.get(user=self.request.user)
            bank_account.account_company = user_company.company
            bank_account.save()
            return redirect(self.success_url)
        except UserCompany.DoesNotExist:
            form.add_error(None, 'Usuário não está associado a nenhuma empresa.')
            return self.form_invalid(form)


class BankAccountDetailView(generic.DetailView):
    model = BankAccount
    template_name = 'bank_account_detail.html'


class BankAccountUpdateView(generic.UpdateView):
    model = BankAccount
    template_name = 'bank_account_update.html'
    form_class = BankAccountForm
    success_url = reverse_lazy('bank_account_list')


class BankAccountDeleteView(generic.DeleteView):
    model = BankAccount
    template_name = 'bank_account_delete.html'
    success_url  = reverse_lazy('bank_account_list')

bank_accounts/templates/bank_account_create.html
{% extends 'base.html' %}
{% block content %}

<div class="container mt-4">
    <h3 class="display-6">Cadastrar Nova Conta Bancária</h3>
    
    <div class="card">
        <div class="card-body">
            <form method="post" class="form">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Salvar Conta Bancária</button>
            </form>
        </div>
    </div>
    <a href="{% url 'bank_account_list' %}" class="btn btn-secondary mt-3">Cancelar e Voltar</a>
</div>

{% endblock %}

bank_accounts/templates/bank_account_delete.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-4">
    <h3 class="display-6">Deletar Conta Bancária</h3>

    <div class="card">
        <div class="card-body">
            <p class="card-text">Tem certeza que deseja exclur a conta de número <strong>{{ object.account_number }}</strong></p>

            <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger mt-3">Deletar</button> 
            </form>

            <a href="{% url 'bank_account_list' %}" class="btn btn-secondary mt-3">Cancelar e Voltar</a>
        </div>
    </div>
</div>

{% endblock %}

bank_accounts/templates/bank_account_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-4">
    <h3 class="display-6">Detalhes da Conta Bancária</h3>

    <div class="card">
        <div class="card-body">
            <h3 class="card-title">{{ object.bank }}</h3>
            <div class="table-responsive">
                <table class="table table-striped table-bordered">
                    <thead class="thead-dark">
                        <tr>
                            <td>Saldo</td>
                            <td>Agência</td>
                            <td>Número da Conta</td>
                            <td>Tipo de Conta</td>
                            <td>Adicionado em</td>
                            <td>Última Alteração</td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>{{ object.account_balance }}</td>
                            <td>{{ object.agency_number }}</td>
                            <td>{{ object.account_number }}</td>
                            <td>{{ object.get_account_type_display }}</td>
                            <td>{{ object.created_at }}</td>
                            <td>{{ object.updated_at }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <a href="{% url 'bank_account_list' %}" class="btn btn-secondary mt-3">Voltar</a>
</div>

{% endblock %}

bank_accounts/templates/bank_account_list.html
{% extends 'base.html' %}

{% block content %}

<div class="row mb-3">
    <div class="col md-6">
        <form method="get" action="{% url 'bank_account_list' %}">
            <div class="input-group">
                <input type="text" class="form-control" name="bank" placeholder="Nome do Banco" value="{{ request.GET.bank}}">
                <button type="submit" class="btn btn-primary">
                    <i class="bi bi-search"></i>
                </button>
            </div>
        </form>
    </div>

    <div class="col md-6">
        <a href="{% url 'bank_account_create' %}" class="btn btn-success float-end">
            <i class="bi bi-plus">Nova Conta Bancária</i>
        </a>
    </div>
</div>

<div class="table-responsive">
    <table class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>Banco</th>
                <th>Número</th>
                <th>Tipo</th>
                <th>Saldo</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for bank_account in bank_accounts %}
            <tr>
                <td>{{ bank_account.bank }}</td>
                <td>{{ bank_account.account_number }}</td>
                <td>{{ bank_account.get_account_type_display }}</td>
                <td>{{ bank_account.account_balance }}</td>
                <td>
                    <a href="{% url 'bank_account_detail' bank_account.id %}" class="btn btn-info btn-sm">
                        <i class="bi bi-eye"></i>
                    </a>

                    <a href="{% url 'bank_account_update' bank_account.id %}" class="btn btn-warning btn-sm">
                        <i class="bi bi-pencil"></i>
                    </a>

                    <a href="{% url 'bank_account_delete' bank_account.id %}" class="btn btn-danger btn-sm">
                        <i class="bi bi-trash"></i>
                    </a>
                </td>
            </tr> 
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

bank_accounts/templates/bank_account_update.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-4">
    <h3 class="display-6">Editar Conta Bancária</h3>

    <div class="card">
        <div class="card-body">
            <form method="post" class="form">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Salvar Conta Bancária</button>
            </form>
        </div>
    </div>

    <a href="{% url 'bank_account_list' %}" class="btn btn-secondary mt-3"> Cancelar e Voltar</a>
</div>

{% endblock %}