app/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('clients.urls')),
    path('', include('suppliers.urls')),
    path('', include('bank_accounts.urls')),
    path('', include('companies.urls')),
    path('', include('transactions.urls'))
]

suppliers/urls.py
from django.urls import path
from .views import SupplierListView, SupplierCreateView, SupplierDetailView, SupplierUpdateView, SupplierDeleteView


urlpatterns = [
    path('suppliers/list/', SupplierListView.as_view(), name='supplier_list'),
    path('suppliers/create/', SupplierCreateView.as_view(), name='supplier_create'),
    path('suppliers/detail/<int:pk>/', SupplierDetailView.as_view(), name='supplier_detail'),
    path('suppliers/update/<int:pk>/', SupplierUpdateView.as_view(), name='supplier_update'),
    path('suppliers/delete/<int:pk>/', SupplierDeleteView.as_view(), name='supplier_delete'),
]

clients/models.py
from django.db import models
from companies.models import Company


class Client(models.Model):
    id = models.IntegerField(primary_key=True)
    client_name = models.CharField(verbose_name='Nome do Cliente', max_length=80, unique=True)
    client_cnpj = models.CharField(verbose_name='CNPJ do Cliente', max_length=14, unique=True)
    client_phone_number = models.CharField(verbose_name='Telefone do Cliente', max_length=11, unique=True)
    client_company = models.ForeignKey(Company, on_delete=models.CASCADE, verbose_name='Empresa da qual é cliente')
    created_at = models.DateTimeField(verbose_name='Data de Criação' ,auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='Data da Última Alteração', auto_now=True)

    class Meta:
        ordering = ['client_name']

    def __str__(self):
        return self.client_name

suppliers/models.py
from django.db import models
from companies.models import Company


class Supplier(models.Model):
    supplier_name = models.CharField(verbose_name='Nome do Fornecedor', max_length=80, unique=True)
    supplier_cnpj = models.CharField(verbose_name='CNPJ do Fornecedor', max_length=14, unique=True, blank=True, null=True)
    supplier_phone_number = models.CharField(verbose_name='Telefone do Fornecedor', max_length=11, unique=True)
    supplier_company = models.ForeignKey(Company, on_delete=models.CASCADE, verbose_name='Empresa da qual é Fornecedor')
    created_at = models.DateTimeField(verbose_name='Data de Criação' ,auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='Data da Última Alteração', auto_now=True)

    class Meta:
        ordering = ['supplier_name']

    def __str__(self):
        return self.supplier_name

suppliers/forms.py
from django import forms
from .models import Supplier



class SupplierForm(forms.ModelForm):

    class Meta:
        model = Supplier
        fields = ['supplier_name', 'supplier_cnpj', 'supplier_phone_number']

        widgets = {
            'supplier_name': forms.TextInput(attrs={'class': 'form-control'}),
            'supplier_cnpj': forms.TextInput(attrs={'class': 'form-control'}),
            'supplier_phone_number': forms.TextInput(attrs={'class': 'form-control'})
        }

        labels = {
            'supplier_name': 'Nome do Fornecedor',
            'supplier_cnpj': 'CNPJ do Fornecedor',
            'supplier_phone_number': 'Número de Telefone do Fornecedor' 
        }

suppliers/views.py
from django.views import generic
from django.urls import reverse_lazy
from .models import Supplier
from .forms import SupplierForm
from authentication.models import UserCompany
from django.shortcuts import redirect


class SupplierListView(generic.ListView):
    model = Supplier
    template_name = 'supplier_list.html'
    context_object_name = 'suppliers'

    def get_queryset(self):
        queryset = super().get_queryset()
        name = self.request.GET.get('supplier_name')

        if name:
            queryset = queryset.filter(supplier_name__icontains=name)

        return queryset


class SupplierCreateView(generic.CreateView):
    model = Supplier
    template_name = 'supplier_create.html'
    form_class = SupplierForm
    success_url = reverse_lazy('supplier_list')

    def form_valid(self, form):
        supplier = form.save(commit=False)
        try:
            user_company = UserCompany.objects.get(user=self.request.user)
            supplier.supplier_company = user_company.company
            supplier.save()
            return redirect(self.success_url)
        except UserCompany.DoesNotExist:
            form.add_error(None, 'Usuário não está associado a nenhuma empresa.')
            return self.form_invalid(form)


class SupplierDetailView(generic.DetailView):
    model = Supplier
    template_name = 'supplier_detail.html'
 

class SupplierUpdateView(generic.UpdateView):
    model = Supplier
    template_name = 'supplier_update.html'
    form_class = SupplierForm
    success_url = reverse_lazy('supplier_list')


class SupplierDeleteView(generic.DeleteView):
    model = Supplier
    template_name = 'supplier_delete.html'
    success_url = reverse_lazy('supplier_list')

suppliers/templates/supplier_create.html
{% extends 'base.html' %}
{% block content %}

<div class="container mt-4">
    <h3 class="display-6">Cadastrar Novo Fornecedor</h3>
    
    <div class="card">
        <div class="card-body">
            <form method="post" class="form">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Salvar Fornecedor</button>
            </form>
        </div>
    </div>
    <a href="{% url 'supplier_list' %}" class="btn btn-secondary mt-3">Cancelar e Voltar</a>
</div>

{% endblock %}

suppliers/templates/supplier_delete.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-4">
    <h3 class="display-6">Deletar Fornecedor</h3>

    <div class="card">
        <div class="card-body">
            <p class="card-text">Tem certeza que deseja exclur o Fornecedor <strong>{{ object.supplier_name }}</strong></p>

            <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger mt-3">Deletar</button> 
            </form>

            <a href="{% url 'client_list' %}" class="btn btn-secondary mt-3">Cancelar e Voltar</a>
        </div>
    </div>
</div>

{% endblock %}

suppliers/templates/supplier_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-4">
    <h3 class="display-6">Detalhes do Fornecedor</h3>

    <div class="card">
        <div class="card-body">
            <h3 class="card-title">{{ object.supplier_name }}</h3>
            <div class="table-responsive">
                <table class="table table-striped table-bordered">
                    <thead class="thead-dark">
                        <tr>
                            {% if object.supplier_cnpj %}
                                <td>CNPJ</td>
                            {% endif %}
                                <td>Telefone</td>
                            <td>Adicionado em</td>
                            <td>Última Alteração</td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            {% if object.supplier_cnpj %}
                                <td>{{ object.supplier_cnpj }}</td>
                            {% endif %}
                            <td>{{ object.supplier_phone_number }}</td>
                            <td>{{ object.created_at }}</td>
                            <td>{{ object.updated_at }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <a href="{% url 'supplier_list' %}" class="btn btn-secondary mt-3">Voltar</a>
</div>

{% endblock %}

suppliers/templates/supplier_list.html
{% extends 'base.html' %}

{% block content %}

<div class="row mb-3">
    <div class="col md-6">
        <form method="get" action="{% url 'supplier_list' %}">
            <div class="input-group">
                <input type="text" class="form-control" name="supplier_name" placeholder="Nome do Fornecedor" value="{{ request.GET.supplier_name }}">
                <button type="submit" class="btn btn-primary">
                    <i class="bi bi-search"></i>
                </button>
            </div>
        </form>
    </div>

    <div class="col md-6">
        <a href="{% url 'supplier_create' %}" class="btn btn-success float-end">
            <i class="bi bi-plus">Novo Fornecedor</i>
        </a>
    </div>
</div>

<div class="table-responsive">
    <table class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>Nome</th>
                <th>CNPJ</th>
                <th>Telefone</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for supplier in suppliers %}
            <tr>
                <td>{{ supplier.supplier_name }}</td>
                {% if supplier.supplier_cnpj %}
                    <td>{{ supplier.supplier_cnpj }}</td>
                {% else %}
                    <td>-</td>
                {% endif %}
                <td>{{ supplier.supplier_phone_number }}</td>
                <td>
                    <a href="{% url 'supplier_detail' supplier.id %}" class="btn btn-info btn-sm">
                        <i class="bi bi-eye"></i>
                    </a>

                    <a href="{% url 'supplier_update' supplier.id %}" class="btn btn-warning btn-sm">
                        <i class="bi bi-pencil"></i>
                    </a>

                    <a href="{% url 'supplier_delete' supplier.id %}" class="btn btn-danger btn-sm">
                        <i class="bi bi-trash"></i>
                    </a>
                </td>
            </tr> 
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

suppliers/templates/supplier_update.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-4">
    <h3 class="display-6">Editar Fornecedor</h3>

    <div class="card">
        <div class="card-body">
            <form method="post" class="form">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Salvar Fornecedor</button>
            </form>
        </div>
    </div>

    <a href="{% url 'supplier_list' %}" class="btn btn-secondary mt-3"> Cancelar e Voltar</a>
</div>

{% endblock %}