app/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('clients.urls')),
    path('', include('suppliers.urls')),
    path('', include('bank_accounts.urls')),
    path('', include('companies.urls')),
    path('', include('transactions.urls'))
]

transactions/urls.py
from django.urls import path
from .views import TransactionCategoryListView, TransactionCategoryCreateView, TransactionCategoryDeleteView, TransactionListView


urlpatterns = [
    path('transactions/categories/list/', TransactionCategoryListView.as_view(), name='transaction_category_list'),
    path('transactions/categories/create/', TransactionCategoryCreateView.as_view(), name='transaction_category_create'),
    path('transactions/categories/delete/<int:pk>/', TransactionCategoryDeleteView.as_view(), name='transaction_category_delete'),
    path('transactions/list/', TransactionListView.as_view(), name='transaction_list'),
]

transactions/models.py
from django.db import models
from bank_accounts.models import BankAccount
from companies.models import CostCenter
from suppliers.models import Supplier
from clients.models import Client
from authentication.models import UserCompany


class TransactionCategory(models.Model):

    class TransactionType(models.IntegerChoices):
        SAÍDA = 0, 'Saída'
        ENTRADA = 1, 'Entrada'
    
    category = models.CharField('Nome da Categoria', max_length=50, unique=True)
    transaction_type = models.IntegerField('Tipo de Categoria', choices=TransactionType.choices, default=TransactionType.ENTRADA)

    def __str__(self):
        return self.category


class Transaction(models.Model):

    class TransactionType(models.IntegerChoices):
        SAÍDA = 0, 'Saída'
        ENTRADA = 1, 'Entrada'

    value = models.FloatField(verbose_name='Valor da Transação')
    description = models.TextField(verbose_name='Descrição da Transação', blank=True, null=True)
    bank_account = models.ForeignKey(BankAccount, verbose_name='Conta bancária utilizada para a transação', on_delete=models.PROTECT)
    transaction_type = models.IntegerField('Tipo de Categoria', choices=TransactionType.choices, default=TransactionType.ENTRADA)
    transaction_category = models.ForeignKey(TransactionCategory, verbose_name='Categoria da Transação', on_delete=models.PROTECT, blank=True, null=True)
    cost_center = models.ForeignKey(CostCenter, verbose_name='Centro de Custo envolvido na Transação', on_delete=models.PROTECT)
    supplier = models.ForeignKey(Supplier, verbose_name='Fornecedor envolvido na Transação', on_delete=models.PROTECT, blank=True, null=True)
    client = models.ForeignKey(Client, verbose_name='Cliente envolvido na Transação', on_delete=models.PROTECT, blank=True, null=True)
    creation_date = models.DateTimeField(verbose_name='Data de Criação da Transação no sistema a pagar ou a receber')
    transaction_date = models.DateTimeField(verbose_name='Data da Operação', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='Data da última atualização', auto_now=True)
    company_associated = models.ForeignKey(UserCompany, verbose_name='Compania envolvida', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.value:.2f} - {self.description}'

transactions/forms.py
from django import forms
from .models import TransactionCategory


class TransactionCategoryForm(forms.ModelForm):

    class Meta:
        model = TransactionCategory
        fields = '__all__'

        widgets = {
            'category':  forms.TextInput(attrs={'class': 'form-control'}),
            'transaction_type': forms.Select(attrs={'class': 'form-control'})
        }

        labels = {
            'category': 'Nome da Categoria',
            'transaction_type': 'Tipo de Transação'
        }

transactions/views.py
from django.views import generic
from .models import TransactionCategory
from .models import Transaction
from .forms import TransactionCategoryForm
from authentication.models import UserCompany
from django.shortcuts import redirect
from django.urls import reverse_lazy


class TransactionCategoryListView(generic.ListView):
    model = TransactionCategory
    template_name = 'transaction_category_list.html'
    context_object_name= 'transaction_categories'

    def get_queryset(self):
        queryset = super().get_queryset()

        transaction_type = self.request.GET.get('transaction_type', '2')
        description = self.request.GET.get('description')
        bank_account = self.request.GET.get('bank_account')
        cost_center = self.request.GET.get('cost_center')


        if transaction_type != '2':
            transaction_type = int(transaction_type)
            queryset = queryset.filter(transaction_type=transaction_type)
        
        if description:
            queryset = queryset.filter(description__icontains=description)
        
        if bank_account:
            queryset = queryset.filter(bank_account__icontains=bank_account)

        if cost_center:
            queryset = queryset.filter(cost_center__icontains=cost_center)
        
        return queryset


class TransactionCategoryCreateView(generic.CreateView):
    model = TransactionCategory
    template_name = 'transaction_category_create.html'
    form_class = TransactionCategoryForm
    success_url = reverse_lazy('transaction_category_list')

    def form_valid(self, form):
        transaction_category = form.save(commit=False)
        try:
            user_company = UserCompany.objects.get(user=self.request.user)
            transaction_category.account_company = user_company.company
            transaction_category.save()
            return redirect(self.success_url)
        except UserCompany.DoesNotExist:
            form.add_error(None, 'Usuário não está associado a nenhuma empresa.')
            return self.form_invalid(form)


class TransactionCategoryDeleteView(generic.DeleteView):
    model = TransactionCategory
    template_name = 'transaction_category_delete.html'
    success_url = reverse_lazy('transaction_category_list')


class TransactionListView(generic.ListView):
    model = Transaction
    template_name = 'transaction_list.html'
    context_object_name= 'transactions'

    def get_queryset(self):
        queryset = super().get_queryset()

        transaction_type = self.request.GET.get('transaction_type', '2')
        description = self.request.GET.get('description')
        bank_account = self.request.GET.get('bank_account')
        cost_center = self.request.GET.get('cost_center')

        if transaction_type != '2':
            transaction_type = int(transaction_type)
            queryset = queryset.filter(transaction_type=transaction_type)

        if description:
            queryset = queryset.filter(description__icontains=description)
     
        if bank_account:
            queryset = queryset.filter(bank_account__icontains=bank_account)

        if cost_center:
            queryset = queryset.filter(cost_center__icontains=cost_center)            

        return queryset

transactions/templates/transaction_category_create.html
{% extends 'base.html' %}
{% block content %}

<div class="container mt-4">
    <h3 class="display-6">Cadastrar Nova Categoria de Transação</h3>
    
    <div class="card">
        <div class="card-body">
            <form method="post" class="form">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Salvar Categoria</button>
            </form>
        </div>
    </div>
    <a href="{% url 'transaction_category_list' %}" class="btn btn-secondary mt-3">Cancelar e Voltar</a>
</div>

{% endblock %}

transactions/templates/transaction_category_delete.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-4">
    <h3 class="display-6">Deletar Categoria</h3>

    <div class="card">
        <div class="card-body">
            <p class="card-text">Tem certeza que deseja exclur a Categoria <strong>{{ object.category }}</strong></p>

            <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger mt-3">Deletar</button> 
            </form>

            <a href="{% url 'transaction_category_list' %}" class="btn btn-secondary mt-3">Cancelar e Voltar</a>
        </div>
    </div>
</div>

{% endblock %}

transactions/templates/transaction_category_list.html
{% extends 'base.html' %}

{% block content %}

<div class="row mb-3">
    <div class="col md-6">
        <form method="get" action="{% url 'transaction_category_list' %}">
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="transaction_type" value="2" {% if request.GET.transaction_type == '2' %}checked{% endif %}  onchange="this.form.submit()">
                <label class="form-check-label">Todos</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="transaction_type" value="1" {% if request.GET.transaction_type == '1' %}checked{% endif %}  onchange="this.form.submit()">
                <label class="form-check-label">Entrada</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="transaction_type" value="0" {% if request.GET.transaction_type == '0' %}checked{% endif %}  onchange="this.form.submit()">
                <label class="form-check-label">Saída</label>
            </div>
        </form>
    </div>

    <div class="col md-6">
        <a href="{% url 'transaction_category_create' %}" class="btn btn-success float-end">
            <i class="bi bi-plus">Novo Categoria</i>
        </a>
    </div>
</div>

<div class="table-responsive">
    <table class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>Nome da Categoria</th>
                <th>Tipo</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for transaction_category in transaction_categories %}
            <tr>
                <td>{{ transaction_category.category }}</td>
                <td>{{ transaction_category.get_transaction_type_display }}</td>
                <td>
                    <a href="{% url 'transaction_category_delete' transaction_category.id %}" class="btn btn-danger btn-sm">
                        <i class="bi bi-trash"></i>
                    </a>
                </td>
            </tr> 
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

transactions/templates/transaction_list.html
{% extends 'base.html' %}

{% block content %}

<div class="row mb-3">
    <div class="col md-9">
        <form method="get" action="{% url 'transaction_list' %}">
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="transaction_type" value="2" {% if not request.GET.transaction_type or request.GET.transaction_type == '2' %}checked{% endif %}  onchange="this.form.submit()">
                <label class="form-check-label">Todos</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="transaction_type" value="1" {% if request.GET.transaction_type == '1' %}checked{% endif %}  onchange="this.form.submit()">
                <label class="form-check-label">Entrada</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="transaction_type" value="0" {% if request.GET.transaction_type == '0' %}checked{% endif %}  onchange="this.form.submit()">
                <label class="form-check-label">Saída</label>
            </div>
            <div class="input-group">
                <input type="text" class="form-control" name="description" placeholder="Descrição" value="{{ request.GET.description}}">
                <input type="text" class="form-control" name="bank_account" placeholder="Conta Bancária" value="{{ request.GET.bank_account}}">
                <input type="text" class="form-control" name="cost_center" placeholder="Centro de Custo" value="{{ request.GET.cost_center}}">
                <button type="submit" class="btn btn-primary">
                    <i class="bi bi-search"></i>
                </button>
            </div>
        </form>
    </div>

    <div class="col md-3">
        <a href="{% url 'transaction_category_list' %}" class="btn btn-primary float-end">Editar Categorias</a>
    </div>
</div>

<div class="table-responsive">
    <table class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>Descrição</th>
                <th>Valor</th>
                <th>Conta bancária</th>
                <th>Tipo</th>
                <th>Centro de Custo</th>
                <th>Data/Hora</th>
            </tr>
        </thead>
        <tbody>
            {% for transaction in transactions %}
            <tr>
                <td>{{ transaction.description }}</td>
                <td>{{ transaction.value }}</td>
                <td>{{ transaction.bank_account }}</td>
                <td>{{ transaction.get_transaction_type_display }}</td>
                <td>{{ transaction.cost_center }}</td>
                <td>{{ transaction.transaction_date }}</td>
            </tr> 
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}